In [324]:
# Importing relevant libraries/modules

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
import lightgbm as lgb
import warnings

In [325]:
# Reading the dataset

df = pd.read_csv('C:\\Users\\Odike Bright Eyindah\\Downloads\\Data_for_UCI_named.csv')
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  
...        ...       ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable  

[10000 rows x 14 columns]

In [326]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [327]:
#Checking null values

df.isna().any()

tau1     False
tau2     False
tau3     False
tau4     False
p1       False
p2       False
p3       False
p4       False
g1       False
g2       False
g3       False
g4       False
stab     False
stabf    False
dtype: bool

In [ ]:
# the dataset is perfectly clean.

In [328]:
#ALso, Checking null values usingt isnull()

df.isnull().sum().sort_values(ascending = True)

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [329]:
# Return the first 5 rows of the dataframe
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [330]:
#more preprocessing: dropping 'stab' column beacuse of its direct relationship with the 'stabf' column
df = df.drop(columns=['stab'])
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  unstable  

[10000 rows x 13 columns]

In [348]:
X = df.iloc[:, 0:12].values
y = df.iloc[:, -1].values

In [349]:
# Spliting the data into 80-20 tarin-test split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=1)

In [345]:
from sklearn.preprocessing import StandardScaler

In [350]:
scaler = StandardScaler() 

In [351]:
X_train = scaler.fit_transform(X_train)

In [352]:
X_test = scaler.transform(X_test)

In [353]:
# RANDOM FOREST CLASSIFIER

In [354]:
from sklearn.ensemble import RandomForestClassifier

In [355]:
# creating a RandomForest classifier
rfc = RandomForestClassifier(n_estimators = 200, random_state =1) 

In [356]:
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=1)

In [359]:
# performing predictions on the test dataset
y_pred = rfc.predict(X_test)

In [360]:
# import metrics to find accuracy
from sklearn import metrics 

In [361]:
from numpy import mean
from numpy import std

In [362]:
# Determining Accuracy_score for the RandomForest Model
print(accuracy_score(y_test, y_pred))

0.925


In [363]:
# Confusion matrix of the RandomForest Model
print(confusion_matrix(y_test,y_pred))

[[ 617   95]
 [  55 1233]]


In [364]:
# Making a classification report on the predicted values of the RandomForest Model
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.92      0.91      0.92      2000
weighted avg       0.92      0.93      0.92      2000



In [373]:
from sklearn.model_selection import RepeatedStratifiedKFold

In [374]:
from sklearn.model_selection import cross_val_score

In [375]:
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [376]:
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [377]:
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [378]:
# using metrics module for overall accuracy calculation/reporting performance of the RandomForest model
print('Accuracy of RandomForest: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy of RandomForest: 0.942 (0.008)


In [379]:
from sklearn.metrics import classification_report, accuracy_score

In [381]:
# EXTRA TREES CLASSIFIER

In [382]:
from sklearn.ensemble import ExtraTreesClassifier

In [383]:
from sklearn.datasets import make_classification

In [384]:
X, y = make_classification(n_features=4, random_state=1)

In [385]:
etc = ExtraTreesClassifier(n_estimators=200, random_state=1)

In [386]:
# Training the model on the training dataset
# the fit function is used to train the model using the training sets as parameters
etc.fit(X_train, y_train)

ExtraTreesClassifier(n_estimators=200, random_state=1)

In [387]:
# performing predictions on the test dataset
y_pred = etc.predict(X_test)

In [302]:
# Determining Accuracy_Score for the ExtraTrees Model 
print(accuracy_score(y_test, y_pred))

0.9305


In [388]:
# Confusion matrix of the ExtraTrees Model
print(confusion_matrix(y_test,y_pred))

[[ 601  111]
 [  28 1260]]


In [304]:
# Making a classification report on the predicted values of the ExtraTrees Model
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

      stable       0.96      0.84      0.90       712
    unstable       0.92      0.98      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.94      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [391]:
# using metrics module for overall accuracy calculation/reporting performance of the ExtraTrees model
print('Accuracy of EXTRATREES MODEL: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy of EXTRATREES MODEL: 0.942 (0.008)


In [392]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1)

In [ ]:
# EXTREME GRADIENT BOOSTING MODEL

In [393]:
# define the extreme gradient boosting model
model = XGBClassifier()

In [394]:
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [396]:
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [397]:
# Determining Accuracy_score for the Xgboost Model
print(accuracy_score(y_test, y_pred))

0.9305


In [398]:
# Confusion matrix of the Xgboost Model
print(confusion_matrix(y_test,y_pred))

[[ 601  111]
 [  28 1260]]


In [390]:
# Making a classification report on the predicted values of the ExtraTrees Model
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

      stable       0.96      0.84      0.90       712
    unstable       0.92      0.98      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.94      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [399]:
# reporting performance of the Xgboost model
print('Accuracy of Xgboost model: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy of Xgboost model: 0.923 (0.023)


In [400]:
# LIGHT GRADIENT BOOSTING MODEL

In [401]:
# defining the Light gradient boosting model
model = lgb.LGBMClassifier()

In [402]:
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [403]:
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [404]:
# Determining Accuracy_score for the lightgbm Model
print(accuracy_score(y_test, y_pred))

0.9305


In [405]:
# Confusion matrix of the lightgbm Model
print(confusion_matrix(y_test,y_pred))

[[ 601  111]
 [  28 1260]]


In [406]:
# Making a classification report on the predicted values of the lightgbm Model
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

      stable       0.96      0.84      0.90       712
    unstable       0.92      0.98      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.94      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [407]:
# report performance of the lightgbm model
print('Accuracy of lightgbm model: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy of lightgbm model: 0.935 (0.027)
